[build]
publish = "dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
command = "npm run build"

[dev]
publish = "public"

[[redirects]]
force = true
from = "/mcp"
status = 200
to = "/.netlify/functions/express-mcp-server"